module.exports = function (config) {
    config.set({
        browsers: ['PhantomJS'],
        frameworks: ['mocha'],
        files: [
           // "node_modules/mocha/mocha.js",
            "node_modules/chai/chai.js",
            "node_modules/sinon/lib/sinon.js",
            "node_modules/sinon/lib/sinon/util/core.js",
            "node_modules/sinon/lib/sinon/extend.js",
            "node_modules/sinon/lib/sinon/typeOf.js",
            "node_modules/sinon/lib/sinon/times_in_words.js",
            "node_modules/sinon/lib/sinon/spy.js",
            "node_modules/sinon/lib/sinon/call.js",
            "node_modules/sinon/lib/sinon/behavior.js",
            "node_modules/sinon/lib/sinon/stub.js",
            "node_modules/sinon/lib/sinon/mock.js",
            "node_modules/sinon/lib/sinon/collection.js",
            "node_modules/sinon/lib/sinon/assert.js",
            "node_modules/sinon/lib/sinon/sandbox.js",
            "node_modules/sinon/lib/sinon/test.js",
            "node_modules/sinon/lib/sinon/test_case.js",
            "node_modules/sinon/lib/sinon/match.js",
            "node_modules/sinon/lib/sinon/format.js",
            "node_modules/sinon/lib/sinon/log_error.js",
            "node_modules/sinon/lib/sinon/util/event.js",
            "node_modules/sinon/lib/sinon/util/fake_server.js",
            "node_modules/sinon/lib/sinon/util/fake_server_with_clock.js",
            "node_modules/sinon/lib/sinon/util/fake_timers.js",
            "node_modules/sinon/lib/sinon/util/fake_xdomain_request.js",
            "node_modules/sinon/lib/sinon/util/fake_xml_http_request.js",
            "node_modules/sinon/lib/sinon/util/timers_ie.js",
            "node_modules/sinon/lib/sinon/util/xdr_ie.js",
            "node_modules/sinon/lib/sinon/util/xhr_ie.js",

            "node_modules/jquery/dist/jquery.min.js",
            "node_modules/angular/angular.js",
            "node_modules/angular-route/angular-route.js",
            "node_modules/angular-mocks/angular-mocks.js",
            "node_modules/angular-validation-match/dist/angular-validation-match.js",

            "scripts/app/app.js",
            "features/Auth/services/auth.js",
            //"features/**/*.js",
            //"features/**/*.js",
            //"scripts/app/directives/*.js",
            //"scripts/app/services/*.js",
            "test/features/Auth/unit/**/*.js",
            //"test/features/Auth/unit/controllers/registration.spec.js"

        ],
        singleRun: true,
        reporters: ['mocha']
    });
}